# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiita', '0002_auto_20170820_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('article_body', models.TextField(max_length=100000)),
            ],
        ),
    ]
